

INSERT INTO [dbo].[Permissions]
           ([RoleCode]
           ,[ActionCode]
           ,[UpdateDate]
           ,[IsRowDeleted]
           ,[CreateUser]
           ,[CreateDate]
           ,[UpdateUser])
     VALUES
           (1
           ,13
           ,GETDATE()
           ,0
           ,'NivaB'
           ,GETDATE()
           ,'NivaB')
GO

INSERT INTO [dbo].[Permissions]
           ([RoleCode]
           ,[ActionCode]
           ,[UpdateDate]
           ,[IsRowDeleted]
           ,[CreateUser]
           ,[CreateDate]
           ,[UpdateUser])
     VALUES
           (2
           ,13
           ,GETDATE()
           ,0
           ,'NivaB'
           ,GETDATE()
           ,'NivaB')
GO

INSERT INTO [dbo].[Permissions]
           ([RoleCode]
           ,[ActionCode]
           ,[UpdateDate]
           ,[IsRowDeleted]
           ,[CreateUser]
           ,[CreateDate]
           ,[UpdateUser])
     VALUES
           (4
           ,13
           ,GETDATE()
           ,0
           ,'NivaB'
           ,GETDATE()
           ,'NivaB')
GO

INSERT INTO [dbo].[Permissions]
           ([RoleCode]
           ,[ActionCode]
           ,[UpdateDate]
           ,[IsRowDeleted]
           ,[CreateUser]
           ,[CreateDate]
           ,[UpdateUser])
     VALUES
           (7
           ,13
           ,GETDATE()
           ,0
           ,'NivaB'
           ,GETDATE()
           ,'NivaB')
GO
