INSERT [Site].[Config] ([Id], [Value], [Description], [App], [SortOrder], [UpdateDate], [IsRowDeleted]) VALUES (N'AlertManhapLastRunningDate', N'3/6/2023 4:59:31 PM', NULL, 0, 1, CAST(N'2023-03-06T16:52:55.230' AS DateTime), 0)
GO
INSERT [Site].[Config] ([Id], [Value], [Description], [App], [SortOrder], [UpdateDate], [IsRowDeleted]) VALUES (N'AlertOfControlEndingLastRunningDate', N'3/6/2023 5:05:13 PM', NULL, 0, 1, CAST(N'2023-03-06T16:51:01.943' AS DateTime), 0)
GO
INSERT [Site].[Config] ([Id], [Value], [Description], [App], [SortOrder], [UpdateDate], [IsRowDeleted]) VALUES (N'ApproveLevelMenifa', N'SoaArch101_PushShalavStatusMenifa/PushShalavStatusMenifaProxy', NULL, 0, 1, CAST(N'2023-06-14T10:00:40.500' AS DateTime), 0)
GO
INSERT [Site].[Config] ([Id], [Value], [Description], [App], [SortOrder], [UpdateDate], [IsRowDeleted]) VALUES (N'ApproveLevelSAP', N'SoaArch102_PushShalavStatusSAP/PushShalavStatusSAPProxy', NULL, 0, 1, CAST(N'2023-06-14T10:01:46.953' AS DateTime), 0)
GO
INSERT [Site].[Config] ([Id], [Value], [Description], [App], [SortOrder], [UpdateDate], [IsRowDeleted]) VALUES (N'MailingList', N'niva.bareli@ness-tech.co.il', NULL, 0, 1, CAST(N'2023-03-06T11:07:05.450' AS DateTime), 0)
GO
INSERT [Site].[Config] ([Id], [Value], [Description], [App], [SortOrder], [UpdateDate], [IsRowDeleted]) VALUES (N'UpdateDocAPI', N'SoaArch100_PushDocumentStatus/PushDocumentStatusProxy', NULL, 0, 1, CAST(N'2023-03-27T13:45:06.863' AS DateTime), 0)
GO
